### PR TITLE
GH-3040: DictionaryFilter.canDrop may return false positive result when dict size exceeds 8k

### LINKED ISSUE #3040: DictionaryFilter.canDrop may return false positive result when dict size exceeds 8k
### Background

I get some data loss reports after upgrading the internal Spark's Parquet from 1.13.1 to 1.14.3, after some experiments, I believe this should be a bug on the Parquet side, and it could be worked around by disabling `spark.sql.parquet.filterPushdown`.

### Analysis

With some debugging, I think the issue was introduced by PARQUET-2432(https://github.com/apache/parquet-java/pull/1278).

The issue is, during the evaluation of `DictionaryFilter.canDrop`(this happens when reading a column that has `PLAIN_DICTIONARY` with pushed predications), when dict size exceeds 8k, only the head 8k was copied

https://github.com/apache/parquet-java/blob/274dc51bc9e5cc880ba3c77c3db826d2a4943965/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/DictionaryPageReader.java#L113

the correct data
```
...
|00001fd0| 34 32 35 34 30 39 0a 00 00 00 37 32 39 33 39 38 |425409....729398|
|00001fe0| 39 35 33 30 0a 00 00 00 39 38 32 30 31 36 39 36 |9530....98201696|
|00001ff0| 34 34 0a 00 00 00 37 33 39 31 32 34 37 38 30 36 |44....7391247806|
|00002000| 0b 00 00 00 31 32 35 32 35 31 36 31 34 31 36 0a |....12525161416.|
|00002010| 00 00 00 38 37 38 35 35 34 34 36 34 35 0b 00 00 |...8785544645...|
|00002020| 00 31 32 32 38 30 38 37 35 39 30 32 0b 00 00 00 |.12280875902....|
...
```

the copied data
```
...
|00001fd0| 34 32 35 34 30 39 0a 00 00 00 37 32 39 33 39 38 |425409....729398|
|00001fe0| 39 35 33 30 0a 00 00 00 39 38 32 30 31 36 39 36 |9530....98201696|
|00001ff0| 34 34 0a 00 00 00 37 33 39 31 32 34 37 38 30 36 |44....7391247806|
|00002000| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
|00002010| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
|00002020| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
...
```

the root cause is 
https://github.com/apache/parquet-java/blob/274dc51bc9e5cc880ba3c77c3db826d2a4943965/parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java#L379

may not read fully if the underlying `InputStream`'s `available` method always returns 0

```
    private static class ReadableByteChannelImpl
        extends AbstractInterruptibleChannel    // Not really interruptible
        implements ReadableByteChannel
    {
     ...
        private static final int TRANSFER_SIZE = 8192;

        public int read(ByteBuffer dst) throws IOException {
            if (!isOpen()) {
                throw new ClosedChannelException();
            }

            int len = dst.remaining();
            int totalRead = 0;
            int bytesRead = 0;
            synchronized (readLock) {
                while (totalRead < len) {
                    int bytesToRead = Math.min((len - totalRead),
                                               TRANSFER_SIZE);
                    if (buf.length < bytesToRead)
                        buf = new byte[bytesToRead];
                    if ((totalRead > 0) && !(in.available() > 0))
                        break; // block at most once
                    try {
                        begin();
                        bytesRead = in.read(buf, 0, bytesToRead);
                    } finally {
                        end(bytesRead > 0);
                    }
                    if (bytesRead < 0)
                        break;
                    else
                        totalRead += bytesRead;
                    dst.put(buf, 0, bytesRead);
                }
                if ((bytesRead < 0) && (totalRead == 0))
                    return -1;

                return totalRead;
            }
        }
        ...
    }
```

### Component(s)

Core

### PR DESCRIPTION
**Pull request by pan3793**
### Rationale for this change

Fixes the data loss issue that reported in #3040

### What changes are included in this PR?

Ensure that `StreamBytesInput#writeInto(ByteBuffer buffer)` copies data fully, even if the underlying `InputStream` does not report available correctly.

### Are these changes tested?

UTs are added, I also tested it with an internal production data loss case.

### Are there any user-facing changes?

Yes, this fixes some data loss cases, and I acknowledge that the bug affects Spark 4.0.0 preview2 which ships Parquet 1.14.2.

Closes #3040

### CODE REVIEW

File: parquet-common/src/test/java/org/apache/parquet/bytes/AvailableAgnosticInputStream.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+import java.io.ByteArrayInputStream;
+
+public class AvailableAgnosticInputStream extends ByteArrayInputStream {
+
+  public AvailableAgnosticInputStream(byte[] buf) {
+    super(buf);
+  }
+
+  // In practice, there are some implementations always return 0 even if they has more data
```
Comment (pan3793) [inline parquet-common/src/test/java/org/apache/parquet/bytes/AvailableAgnosticInputStream.java:30]: in my case, the underlying `IntputStream` is `H1SeekableInputStream`

**Comment by pan3793** [comment]
cc @gszadovszky @wgtmac @Fokko

File: parquet-common/src/test/java/org/apache/parquet/bytes/TestBytesInput.java [hunk 2]
```diff
@@ -140,6 +140,20 @@ public void testFromInputStream() throws IOException {
...
+  @Test
+  public void testFromLargeAvailableAgnosticInputStream() throws IOException {
+    // allocate a bytes that large than
+    // java.nio.channel.Channels.ReadableByteChannelImpl.TRANSFER_SIZE = 8192
+    byte[] data = new byte[9 * 1024];
+    RANDOM.nextBytes(data);
+    byte[] input = new byte[data.length + 10];
+    RANDOM.nextBytes(input);
+    System.arraycopy(data, 0, input, 0, data.length);
+    Supplier<BytesInput> factory = () -> BytesInput.from(new AvailableAgnosticInputStream(input), 9 * 1024);
```
Comment (wgtmac) [inline parquet-common/src/test/java/org/apache/parquet/bytes/TestBytesInput.java:152]: What about using an anonymous class here instead of adding a new file?

File: parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java [hunk 3]
```diff
@@ -376,7 +377,11 @@ void writeInto(ByteBuffer buffer) {
         ByteBuffer workBuf = buffer.duplicate();
         int pos = buffer.position();
         workBuf.limit(pos + byteCount);
-        Channels.newChannel(in).read(workBuf);
+        ReadableByteChannel channel = Channels.newChannel(in);
+        int remaining = byteCount;
+        while (remaining > 0) {
+          remaining -= channel.read(workBuf);
```
Comment (wgtmac) [inline parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java:383]: Is `remaining` reliable? Should we check the return value of `channel.read(workBuf)`?

Comment (pan3793) [reply parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java]: added a check to detect EOF case

**Review by wgtmac — APPROVED** [review]
+1. Thanks @pan3793!

File: parquet-common/src/test/java/org/apache/parquet/bytes/AvailableAgnosticInputStream.java (hunk 1 above)
Comment (Fokko) [reply parquet-common/src/test/java/org/apache/parquet/bytes/AvailableAgnosticInputStream.java:30]: Out of curiosity. Why are you using `H1SeekableInputStream`? This one is related to Hadoop 1.

Comment (pan3793) [reply parquet-common/src/test/java/org/apache/parquet/bytes/AvailableAgnosticInputStream.java:30]: My test code is
(sorry, the file contains private data so I can not share)
```
public class MyDictionaryFilterTest {

  private static final Configuration conf = new Configuration();
  List<ColumnChunkMetaData> ccmd;
  ParquetFileReader reader;
  DictionaryPageReadStore dictionaries;
  private Path file = new Path("/Users/chengpan/Temp/part-2bb8404a-f6e5-4e9f-9161-f749c4bf46d0-2-2222");

  @Before
  public void setUp() throws Exception {
    reader = ParquetFileReader.open(conf, file);
    ParquetMetadata meta = reader.getFooter();
    ccmd = meta.getBlocks().get(0).getColumns();
    dictionaries = reader.getDictionaryReader(meta.getBlocks().get(0));
  }

  @After
  public void tearDown() throws Exception {
    reader.close();
  }

  @Test
  public void testEqBinary() throws Exception {
    BinaryColumn b = binaryColumn("source_id");
    FilterPredicate pred = eq(b, Binary.fromString("5059661515"));

    assertFalse(canDrop(pred, ccmd, dictionaries));
  }
}
```

Comment (Fokko) [reply parquet-common/src/test/java/org/apache/parquet/bytes/AvailableAgnosticInputStream.java:30]: Thanks, this is very helpful!

**Review by gszadovszky — APPROVED** [review]

File: parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java [hunk 4]
```diff
@@ -376,7 +378,15 @@ void writeInto(ByteBuffer buffer) {
         ByteBuffer workBuf = buffer.duplicate();
         int pos = buffer.position();
         workBuf.limit(pos + byteCount);
-        Channels.newChannel(in).read(workBuf);
```
Comment (ConeyLiu) [inline parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java:379]: Is there any other place that is used like this?

Comment (pan3793) [reply parquet-common/src/main/java/org/apache/parquet/bytes/BytesInput.java:379]: I went through the [original PR](https://github.com/apache/parquet-java/pull/1278) and found nothing else, it would be great if others have a double check.

**Comment by Fokko** [comment]
Thanks @pan3793 for finding and fixing this, and thanks @wgtmac @ConeyLiu and @gszadovszky for the review 🙌
