### PR TITLE
GH-3320: Ensure parquet reader does not fail due to incorrect statistics

### LINKED ISSUE #3320: Parquet read fails in certain scenarios for files written by parquet-go
### Describe the enhancement requested

Parquet-go can write extra entries in the column index for 1 column chunk. This causes Parquet java to fail with java.lang.ArrayIndexOutOfBoundsException when using column indexes.
 - Parquet java expects the same number of entries in column index and offset index (one entry per data page).
 - When they don't match, the reader seems to be trying to read a non existent page (based on the column stats) and fails. (stacktrace below)

Structure of indexes which lead to the failure:
```
DEBUG: COLUMN1 ColumnIndex=5 stats
  Entry 0: nullPage=false, nullCount=0, min='', max=''
  Entry 1: nullPage=false, nullCount=0, min='xyz', max='abc'
  Entry 2: nullPage=false, nullCount=0, min='xyz', max='abc'
  Entry 3: nullPage=false, nullCount=0, min='xyz', max='abc'
  Entry 4: nullPage=false, nullCount=0, min='xyz', max='abc'

DEBUG: COLUMN1 OffsetIndex=4 pages
  Entry 0: offset=..., compressedSize=..., firstRowIndex=0
  Entry 1: offset=..., compressedSize=..., firstRowIndex=30
  Entry 2: offset=..., compressedSize=..., firstRowIndex=60
  Entry 3: offset=..., compressedSize=..., firstRowIndex=90

(Here we have 1 additional column index for the same data page)
```

There could be potentially 2 ways to fix this:
1. Detect inconsistent metadata and do not rely on column index for unsuitable/incomplete metadata. Log a WARN and continue reading the file without index, which will correctly read the file.
2. Clearly throw an exception indicating the missing/unhandled metadata (in this case, the mismatch in number of column/offset index), so user can disable column index or correct upstream.

Stacktrace: 
```
        at org.apache.parquet.internal.column.columnindex.OffsetIndexBuilder$OffsetIndexImpl.getFirstRowIndex(OffsetIndexBuilder.java:66)
        at org.apache.parquet.internal.filter2.columnindex.RowRanges.create(RowRanges.java:144) 
        at org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter.applyPredicate(ColumnIndexFilter.java:189)
        at org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter.visit(ColumnIndexFilter.java:126)
        at org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter.visit(ColumnIndexFilter.java:57) 
        at org.apache.parquet.filter2.predicate.Operators$NotEq.accept(Operators.java:192)
        at org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter$1.visit(ColumnIndexFilter.java:87) 
        at org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter$1.visit(ColumnIndexFilter.java:82) 
        at org.apache.parquet.filter2.compat.FilterCompat$FilterPredicateCompat.accept(FilterCompat.java:149) 
        at org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter.calculateRowRanges(ColumnIndexFilter.java:82)
        at org.apache.parquet.hadoop.ParquetFileReader.getRowRanges(ParquetFileReader.java:1219) 
        at org.apache.parquet.hadoop.ParquetFileReader.getFilteredRecordCount(ParquetFileReader.java:875) 
...
```

### Component(s)

_No response_

### PR DESCRIPTION
**Pull request by ArnavBalyan**
### Rationale for this change
 - Parquet reader fails if upstream writes wrong statistics in column index vs offset index. 
 - Ensure parquet java can still read the file and ignore corrupt metadata in such cases.
 - Added UT to ensure existing behaviour is preserved.
 - Fixes #3320

### Are these changes tested?
 - Yes

### Are there any user-facing changes?
 - Yes

### CODE REVIEW

File: parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java [hunk 1]
```diff
@@ -220,4 +225,35 @@ public RowRanges visit(Not not) {
...
+   *
+   * @param columnIndex the column index to validate
+   * @param offsetIndex the offset index to validate
+   * @param columnPath the column path for error reporting
+   * @return true if metadata is valid and safe to use, false if corrupt and should be ignored
+   */
+  private static boolean isValidMetadata(ColumnIndex columnIndex, OffsetIndex offsetIndex, ColumnPath columnPath) {
+    if (columnIndex == null || offsetIndex == null) {
+      return true;
+    }
```
Comment (gszadovszky) [inline parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java]: Based on the code it seems they cannot be null at this stage.

File: parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java [hunk 2]
```diff
@@ -650,4 +660,75 @@ public void testFilteringWithProjection() throws IOException {
             false,
             true));
   }
+
+  @Test
+  public void testValidMetadata() throws Exception {
```
Comment (wgtmac) [inline parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java]: Shouldn't we test invalid page index?

File: parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java [hunk 3]
```diff
@@ -220,4 +225,35 @@ public RowRanges visit(Not not) {
...
+
+  /**
+   * Validates that column index and offset index metadata are consistent and can be used safely.
+   *
+   * @param columnIndex the column index to validate
+   * @param offsetIndex the offset index to validate
+   * @param columnPath the column path for error reporting
+   * @return true if metadata is valid and safe to use, false if corrupt and should be ignored
+   */
+  private static boolean isValidMetadata(ColumnIndex columnIndex, OffsetIndex offsetIndex, ColumnPath columnPath) {
```
Comment (wgtmac) [inline parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java]: It might be misleading to readers that this function does not validate everything but just `columnIndex.getMinValues().size()` vs `offsetIndex.getPageCount()`. But I'm not sure if we want to pay for the cost of validating everything.

File: parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java (hunk 1 above)
Comment (ArnavBalyan) [reply parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java]: updated thanks

File: parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java (hunk 3 above)
Comment (ArnavBalyan) [reply parquet-column/src/main/java/org/apache/parquet/internal/filter2/columnindex/ColumnIndexFilter.java]: updated to `isValidIndexSize`, was initially planned to be a general pre-check which can be enhanced in the future. For now restricting to index size.

File: parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java (hunk 2 above)
Comment (ArnavBalyan) [reply parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java]: we need the buggy parquet-go lib to create the invalid index, current check is in the column read flow, will only fail if the upstream wrote invalid data, is there a better way to test it?

**Review by gszadovszky — APPROVED** [review]
LGTM.
@wgtmac, could you check if you're OK with the answers/changes?

File: parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java (hunk 2 above)
Comment (wgtmac) [reply parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java]: If this test does not cover the new case, perhaps we can simply revert all changes in this file?

A better way would be uploading the corrupted data produced by parquet-go to https://github.com/apache/parquet-testing/tree/master/bad_data. But I do not think it worths the effort...

Comment (ArnavBalyan) [reply parquet-hadoop/src/test/java/org/apache/parquet/hadoop/TestColumnIndexFiltering.java]: updated thanks
