### PR TITLE
GH-2992: Gate LocalTimestamp references in AvroSchemaConverter

### LINKED ISSUE #2992: Parquet 1.14.2-RC1 breaks compat with Avro 1.7, 1.8, 1.9
### Describe the bug, including details regarding any error messages, version, and platform.

AvroSchemaConverter references Avro logical type converters that aren't available in Avro versions below 1.10: See more here: https://github.com/apache/parquet-java/pull/1115/files#r1721966099

For reference, these are the local TIMESTAMP converters available in Avro 1.10+: https://github.com/apache/avro/blob/release-1.10.0/lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java#L172-L194

Whereas in 1.9.2, only `timestampMillis`/`timestampMicros` area available: https://github.com/apache/avro/blob/release-1.9.2/lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java#L158-L168

### Component(s)

Avro

### PR DESCRIPTION
**Pull request by clairemcginty**
### Rationale for this change

See linked [issue](https://github.com/apache/parquet-java/issues/2992); AvroSchemaConverter references Avro classes and methods that don't exist before Avro 1.10

### What changes are included in this PR?

Performs an Avro version check to silo references to local timestamp classes.

### Are these changes tested?

I've tested them locally on one of my projects using Avro 1.8... unfortunately there isn't a great way to unit-test this :/

### Are there any user-facing changes?

This should preserve the existing behavior for Avro 1.8 users while unlocking the new LocalTimestamp types for 1.10+ users.

Closes #2992

### CODE REVIEW

**Comment by clairemcginty** [comment]
cc @RustedBones , can you take a look at this fix as well?

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java [hunk 1]
```diff
@@ -605,4 +611,14 @@ private static String namespace(String name, Map<String, Integer> names) {
     Integer nameCount = names.merge(name, 1, (oldValue, value) -> oldValue + 1);
     return nameCount > 1 ? name + nameCount : null;
   }
+
+  /* Avro <= 1.9 does not support conversions to LocalTimestamp{Micros, Millis} classes */
+  private static boolean avroVersionSupportsLocalTimestampTypes() {
```
Comment (Fokko) [inline parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:616]: What do you think of mocking this method to capture the behavior of supporting and not-supporting local timestamps.

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java [hunk 2]
```diff
@@ -538,7 +544,7 @@ public Optional<LogicalType> visit(
             LogicalTypeAnnotation.TimeUnit unit = timestampLogicalType.getUnit();
             boolean isAdjustedToUTC = timestampLogicalType.isAdjustedToUTC();
 
-            if (isAdjustedToUTC) {
+            if (isAdjustedToUTC || !avroVersionSupportsLocalTimestampTypes()) {
```
Comment (Fokko) [inline parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:547]: If local timestamps aren't supported, isn't it more safe to default to `empty()`? Otherwise, we're mixing up types.

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java (hunk 1 above)
Comment (clairemcginty) [reply parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:616]: I'll give it a try with Powermock!

I might start a thread on the mailing list this week discussing Avro version support more broadly, to formalize which Avro versions are currently supported/any planned EOL dates? I've been thinking it would also be good to have some automated testing of parquet-avro on different Avro versions... it would just be a little complicated to set up since we'd need either a separate Maven module per supported Avro version, or some very clever classloading :)

Comment (Fokko) [reply parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:616]: Hey @clairemcginty, that's a good idea!

What do we consider the lower-bound? :D Avro 1.8.2 is May 2017, so that's pretty old, but I'm aware of some breaking API changes because we exposed some Jackson classes in the public API.

To do cross-testing, we can do something similar to we do with Hadoop 2, you can get some inspiration there: https://github.com/apache/parquet-java/blob/d4384d3f2e7703fab6363fd9cd80a001e9561db2/pom.xml#L638-L643

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java (hunk 2 above)
Comment (clairemcginty) [reply parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:547]: sorry for the confusion! changes to both methods should be needed; I've added test cases to `TestAvroSchemaConverter` that demonstrate the issue and fail without my changes to `AvroSchemaConverter` applied. Basically, we don't want to try to assign a logical type that doesn't exist in the user's Avro version.

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java (hunk 1 above)
Comment (clairemcginty) [reply parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:616]: I think 1.8 is a reasonable lower bound! for context on our use case, we use the [Beam](https://github.com/apache/beam) library, which until very recently was tightly coupled with 1.8. Things are now more flexible, but there's a lot of inertia surrounding 1.8 -- the breaking changes surrounding logical types make it a non-trivial upgrade 😅 

I'll take a look at the hadoop setup! Avro is a bit tricky because we need to both set the Avro-compiler version, and load the Avro core library, for whatever version of Avro we want to test...

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java (hunk 2 above)
Comment (Fokko) [reply parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:547]: No problem, thanks for adding the test 👍

File: parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java (hunk 1 above)
Comment (Fokko) [reply parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java:616]: Thanks for the context, that helps. I see that 1.8.2 is [still in there](https://github.com/apache/beam/blob/b3a874f476646676bf7eb909cae738a696f36303/sdks/java/extensions/avro/build.gradle#L40), so that sounds reasonable to me 👍

**Review by Fokko — APPROVED** [review]
