### PR TITLE
GH-3449: Fix BinaryStats int overflow

### LINKED ISSUE #3449: Fix BinaryStats int overflow
### Describe the bug, including details regarding any error messages, version, and platform.

`BinaryStatistics.isSmallerThan()` computes `min.length() + max.length()` as `int + int`. When a binary column contains values >= 2^30 bytes (1 GB), this sum overflows to a negative number, which is then incorrectly evaluated as smaller than `MAX_STATS_SIZE` (4096). This causes the full multi-GB min/max statistics to be serialized into the Thrift footer instead of being dropped, resulting in a corrupted Parquet file whose footer exceeds the 4-byte length field and cannot be read back.

### Component(s)

_No response_

### PR DESCRIPTION
**Pull request by Jiayi-Wang-db**
### Rationale for this change
`BinaryStatistics.isSmallerThan()` computes `min.length() + max.length()` as `int + int`. When a binary column contains values >= 2^30 bytes (1 GB), this sum overflows to a negative number, which is then incorrectly evaluated as smaller than `MAX_STATS_SIZE` (4096). This causes the full multi-GB min/max statistics to be serialized into the Thrift footer instead of being dropped, resulting in a corrupted Parquet file whose footer exceeds the 4-byte length field and cannot be read back.

### What changes are included in this PR?
Promote int arithmetic to long before addition in `BinaryStatistics.isSmallerThan()` and `isSmallerThanWithTruncation()` to prevent integer overflow when binary values are very large.

### Are these changes tested?
Yes. Added a unit test in TestStatistics that creates a 1 GB binary value and asserts isSmallerThan(4096) correctly returns false.

### Are there any user-facing changes?
Parquet files with very large binary values (>= 1 GB) will no longer have corrupted footers. The oversized statistics are now correctly dropped, producing a valid and readable file.

Closes #3449

### CODE REVIEW

File: parquet-column/src/test/java/org/apache/parquet/column/statistics/TestStatistics.java [hunk 1]
```diff
@@ -927,4 +927,16 @@ public void testNoopStatistics() {
     assertThrows(UnsupportedOperationException.class, stats::minAsString);
     assertThrows(UnsupportedOperationException.class, () -> stats.isSmallerThan(0));
   }
+
+  @Test
+  public void testBinaryIsSmallerThanNoOverflowForLargeValues() {
+    PrimitiveType type = Types.required(BINARY).named("test_binary");
+    Statistics<?> stats = Statistics.getBuilderForReading(type).build();
+
+    byte[] largeValue = new byte[1_073_741_824]; // 2^30 = 1 GB
```
Comment (wgtmac) [inline parquet-column/src/test/java/org/apache/parquet/column/statistics/TestStatistics.java]: Do we really need to allocate such large memory in the test?

Comment (Jiayi-Wang-db) [reply parquet-column/src/test/java/org/apache/parquet/column/statistics/TestStatistics.java]: Thanks, fixed.
